export const DEFAULT_TASK = [
  {
    id: 1,
    text: "Học lập trình web với React",
    date: "2024-10-03",
    status: "done",
    priority: "high",
    category: "học tập",
  },
  {
    id: 2,
    text: "Gửi email nộp bài tập về nhà",
    date: "2024-10-29",
    status: "todo",
    priority: "medium",
    category: "công việc",
  },
  {
    id: 3,
    text: "Học từ vựng tiếng anh mỗi ngày",
    date: "2024-12-07",
    status: "todo",
    priority: "low",
    category: "học tập",
  },
  {
    id: 4,
    text: "Viết tiểu luận môn Triết học",
    date: "2024-10-19",
    status: "todo",
    priority: "high",
    category: "học tập",
  },
  {
    id: 5,
    text: "Học Java OOP",
    date: "2024-11-19",
    status: "todo",
    priority: "high",
    category: "học tập",
  },
  {
    id: 6,
    text: "Học toán rời rạc",
    date: "2024-12-19",
    status: "todo",
    priority: "high",
    category: "học tập",
  },
];
